{% set name = "langchain-text-splitters" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_text_splitters-{{ version }}.tar.gz
  sha256: 11cb7ca3694e5bdd342bc16d3875b7f7381651d4a53cbb91d34f22412ae16443

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - langchain-core >=0.3.29,<0.4.0
  run_constrained:
    - lxml >=4.9.3,<6.0.0
    - beautifulsoup4 >=4.12.3,<5.0.0

test:
  imports:
    - langchain_text_splitters
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/text-splitters
  summary: LangChain text splitting utilities
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - pavelzw
