{% set name = "langchain-text-splitters" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_text_splitters-{{ version }}.tar.gz
  sha256: 116d4b9f2a22dda357d0b79e30acf005c5518177971c66a9f1ab0edfdb0f912e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - langchain-core <1.0.0,>=0.3.51
  run_constrained:
    - lxml >=4.9.3,<6.0.0
    - beautifulsoup4 >=4.12.3,<5.0.0

test:
  imports:
    - langchain_text_splitters
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/text-splitters
  summary: LangChain text splitting utilities
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - pavelzw
