{% set name = "langchain-text-splitters" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_text_splitters-{{ version }}.tar.gz
  sha256: 34861abe7c07d9e49d4dc852d0129e26b32738b60a74486853ec9b6d6a8e01d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - pip >=25.2
    - python >={{ python_min }}
    - langchain-core >=1.2.13,<2.0.0

test:
  imports:
    - langchain_text_splitters
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/text-splitters
  summary: LangChain text splitting utilities
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - pavelzw
